name: Build

on: 
  workflow_call:

env:
  GODOT_ANDROID_KEYSTORE_RELEASE_PATH: ${{ github.workspace }}/release.keystore 
  GODOT_ANDROID_KEYSTORE_RELEASE_USER: Unknown
  GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD: 123456

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.platform.system }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    strategy:
      fail-fast: false
      matrix:
        platform: 
          - name: Windows
            system: "ubuntu-latest"
            extension: ".exe"
          - name: macOS
            system: "macos-latest"
            extension: ".app"
          - name: Linux
            system: "ubuntu-latest"
            extension: ".x86_64"
          - name: Web
            system: "ubuntu-latest"
            extension: ".html"
          - name: Android
            system: "ubuntu-latest"
            extension: ".apk"
          # - name: iOS
          #   system: "macos-latest"
          #   extension: ".ipa"
    steps:
        # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Check if the project is using C#
      # Web job will be skipped if the project is using C#.
      - name: Check if project is using C#
        id: check_dotnet
        run: |
          if [ -f *.csproj ]; then
            echo "using_dotnet=true" >> $GITHUB_OUTPUT
            echo "C# project detected."
            if [ "${{ matrix.platform.name }}" == "Web" ]; then
              echo "web_csharp=true" >> $GITHUB_OUTPUT
              echo "Godot 4.x does not support building C# projects for Web platform."
            fi
          else
            echo "using_dotnet=false" >> $GITHUB_OUTPUT
          fi

      # Setup .NET
      - name: Setup .NET SDK
        if: steps.check_dotnet.outputs.using_dotnet == 'true'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Build C# Projects
        if: steps.check_dotnet.outputs.using_dotnet == 'true'
        run: |
            dotnet restore
            dotnet build

      # Setup Godot
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          # Version must include major, minor, and patch, and be >= 4.0.0
          # Pre-release label is optional.
          version: 4.3.0 # also valid: 4.0.0.rc1 or 4.0.0, etc
          use-dotnet: ${{ steps.check_dotnet.outputs.using_dotnet }}
          include-templates: true

      - name: Verify Godot Version
        run: |
          godot --version

      # Setup android
      - name: Set up JDK 17
        if: matrix.platform.name == 'Android'
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        if: matrix.platform.name == 'Android'
        uses: android-actions/setup-android@v3

      - name: Generate Keystore
        if: matrix.platform.name == 'Android'
        run: |
          if [ ! -f $GODOT_ANDROID_KEYSTORE_RELEASE_PATH ]; then
            keytool -genkey -v -keystore release.keystore -alias $GODOT_ANDROID_KEYSTORE_RELEASE_USER -keyalg RSA -keysize 2048 -validity 10000 \
              -storepass $GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD -keypass $GODOT_ANDROID_KEYSTORE_RELEASE_PASSWORD -dname "CN=Unknown, OU=Unknown, O=Unknown, L=Unknown, S=Unknown, C=Unknown"
          fi
          env

      # Build the project for each platform
      - name: Build Godot Solutions
        if: steps.check_dotnet.outputs.web_csharp != 'true'
        run: godot --headless --build-solutions --quit || exit 0
        
      - name: Export Project
        if: steps.check_dotnet.outputs.web_csharp != 'true'
        run: |
          mkdir -v -p build
          godot --headless --verbose --export-release "${{ matrix.platform.name }}" ./build/${{ github.event.repository.name }}${{ matrix.platform.extension }}

      # Compress the build files and upload them as an artifact
      - name: Compress build files
        if: steps.check_dotnet.outputs.web_csharp != 'true'
        run: |
          cd build
          sudo zip -r ./${{ matrix.platform.name }}.zip *

      - name: Display structure of build files
        continue-on-error: true
        run: ls -R ./build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.name }}
          path: ./build/${{ matrix.platform.name }}.zip